// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	application "log-parser/internal/application"

	mock "github.com/stretchr/testify/mock"
)

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: archivePath
func (_m *MockParser) Parse(archivePath string) (application.ParseResult, error) {
	ret := _m.Called(archivePath)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 application.ParseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (application.ParseResult, error)); ok {
		return rf(archivePath)
	}
	if rf, ok := ret.Get(0).(func(string) application.ParseResult); ok {
		r0 = rf(archivePath)
	} else {
		r0 = ret.Get(0).(application.ParseResult)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(archivePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - archivePath string
func (_e *MockParser_Expecter) Parse(archivePath interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", archivePath)}
}

func (_c *MockParser_Parse_Call) Run(run func(archivePath string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(_a0 application.ParseResult, _a1 error) *MockParser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(string) (application.ParseResult, error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveArchive provides a mock function with given fields: rel
func (_m *MockParser) ResolveArchive(rel string) (string, error) {
	ret := _m.Called(rel)

	if len(ret) == 0 {
		panic("no return value specified for ResolveArchive")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(rel)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(rel)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParser_ResolveArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveArchive'
type MockParser_ResolveArchive_Call struct {
	*mock.Call
}

// ResolveArchive is a helper method to define mock.On call
//   - rel string
func (_e *MockParser_Expecter) ResolveArchive(rel interface{}) *MockParser_ResolveArchive_Call {
	return &MockParser_ResolveArchive_Call{Call: _e.mock.On("ResolveArchive", rel)}
}

func (_c *MockParser_ResolveArchive_Call) Run(run func(rel string)) *MockParser_ResolveArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockParser_ResolveArchive_Call) Return(_a0 string, _a1 error) *MockParser_ResolveArchive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParser_ResolveArchive_Call) RunAndReturn(run func(string) (string, error)) *MockParser_ResolveArchive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
