// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "log-parser/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// LogMeta provides a mock function with given fields: ctx, logID
func (_m *MockService) LogMeta(ctx context.Context, logID int64) (domain.Log, error) {
	ret := _m.Called(ctx, logID)

	if len(ret) == 0 {
		panic("no return value specified for LogMeta")
	}

	var r0 domain.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Log, error)); ok {
		return rf(ctx, logID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Log); ok {
		r0 = rf(ctx, logID)
	} else {
		r0 = ret.Get(0).(domain.Log)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, logID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_LogMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogMeta'
type MockService_LogMeta_Call struct {
	*mock.Call
}

// LogMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - logID int64
func (_e *MockService_Expecter) LogMeta(ctx interface{}, logID interface{}) *MockService_LogMeta_Call {
	return &MockService_LogMeta_Call{Call: _e.mock.On("LogMeta", ctx, logID)}
}

func (_c *MockService_LogMeta_Call) Run(run func(ctx context.Context, logID int64)) *MockService_LogMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_LogMeta_Call) Return(_a0 domain.Log, _a1 error) *MockService_LogMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_LogMeta_Call) RunAndReturn(run func(context.Context, int64) (domain.Log, error)) *MockService_LogMeta_Call {
	_c.Call.Return(run)
	return _c
}

// NodeDetail provides a mock function with given fields: ctx, nodeID
func (_m *MockService) NodeDetail(ctx context.Context, nodeID int64) (domain.NodeDetail, error) {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for NodeDetail")
	}

	var r0 domain.NodeDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.NodeDetail, error)); ok {
		return rf(ctx, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.NodeDetail); ok {
		r0 = rf(ctx, nodeID)
	} else {
		r0 = ret.Get(0).(domain.NodeDetail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_NodeDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeDetail'
type MockService_NodeDetail_Call struct {
	*mock.Call
}

// NodeDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID int64
func (_e *MockService_Expecter) NodeDetail(ctx interface{}, nodeID interface{}) *MockService_NodeDetail_Call {
	return &MockService_NodeDetail_Call{Call: _e.mock.On("NodeDetail", ctx, nodeID)}
}

func (_c *MockService_NodeDetail_Call) Run(run func(ctx context.Context, nodeID int64)) *MockService_NodeDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_NodeDetail_Call) Return(_a0 domain.NodeDetail, _a1 error) *MockService_NodeDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_NodeDetail_Call) RunAndReturn(run func(context.Context, int64) (domain.NodeDetail, error)) *MockService_NodeDetail_Call {
	_c.Call.Return(run)
	return _c
}

// Ports provides a mock function with given fields: ctx, nodeID
func (_m *MockService) Ports(ctx context.Context, nodeID int64) ([]domain.Port, error) {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for Ports")
	}

	var r0 []domain.Port
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Port, error)); ok {
		return rf(ctx, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Port); ok {
		r0 = rf(ctx, nodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Port)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Ports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ports'
type MockService_Ports_Call struct {
	*mock.Call
}

// Ports is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID int64
func (_e *MockService_Expecter) Ports(ctx interface{}, nodeID interface{}) *MockService_Ports_Call {
	return &MockService_Ports_Call{Call: _e.mock.On("Ports", ctx, nodeID)}
}

func (_c *MockService_Ports_Call) Run(run func(ctx context.Context, nodeID int64)) *MockService_Ports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_Ports_Call) Return(_a0 []domain.Port, _a1 error) *MockService_Ports_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Ports_Call) RunAndReturn(run func(context.Context, int64) ([]domain.Port, error)) *MockService_Ports_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessArchive provides a mock function with given fields: ctx, rel
func (_m *MockService) ProcessArchive(ctx context.Context, rel string) (int64, error) {
	ret := _m.Called(ctx, rel)

	if len(ret) == 0 {
		panic("no return value specified for ProcessArchive")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, rel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, rel)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ProcessArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessArchive'
type MockService_ProcessArchive_Call struct {
	*mock.Call
}

// ProcessArchive is a helper method to define mock.On call
//   - ctx context.Context
//   - rel string
func (_e *MockService_Expecter) ProcessArchive(ctx interface{}, rel interface{}) *MockService_ProcessArchive_Call {
	return &MockService_ProcessArchive_Call{Call: _e.mock.On("ProcessArchive", ctx, rel)}
}

func (_c *MockService_ProcessArchive_Call) Run(run func(ctx context.Context, rel string)) *MockService_ProcessArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ProcessArchive_Call) Return(_a0 int64, _a1 error) *MockService_ProcessArchive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ProcessArchive_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockService_ProcessArchive_Call {
	_c.Call.Return(run)
	return _c
}

// Topology provides a mock function with given fields: ctx, logID
func (_m *MockService) Topology(ctx context.Context, logID int64) (domain.Topology, error) {
	ret := _m.Called(ctx, logID)

	if len(ret) == 0 {
		panic("no return value specified for Topology")
	}

	var r0 domain.Topology
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Topology, error)); ok {
		return rf(ctx, logID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Topology); ok {
		r0 = rf(ctx, logID)
	} else {
		r0 = ret.Get(0).(domain.Topology)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, logID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Topology_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topology'
type MockService_Topology_Call struct {
	*mock.Call
}

// Topology is a helper method to define mock.On call
//   - ctx context.Context
//   - logID int64
func (_e *MockService_Expecter) Topology(ctx interface{}, logID interface{}) *MockService_Topology_Call {
	return &MockService_Topology_Call{Call: _e.mock.On("Topology", ctx, logID)}
}

func (_c *MockService_Topology_Call) Run(run func(ctx context.Context, logID int64)) *MockService_Topology_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_Topology_Call) Return(_a0 domain.Topology, _a1 error) *MockService_Topology_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Topology_Call) RunAndReturn(run func(context.Context, int64) (domain.Topology, error)) *MockService_Topology_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
