// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	application "log-parser/internal/application"
	domain "log-parser/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateLog provides a mock function with given fields: ctx, path
func (_m *MockStore) CreateLog(ctx context.Context, path string) (int64, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for CreateLog")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreateLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLog'
type MockStore_CreateLog_Call struct {
	*mock.Call
}

// CreateLog is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStore_Expecter) CreateLog(ctx interface{}, path interface{}) *MockStore_CreateLog_Call {
	return &MockStore_CreateLog_Call{Call: _e.mock.On("CreateLog", ctx, path)}
}

func (_c *MockStore_CreateLog_Call) Run(run func(ctx context.Context, path string)) *MockStore_CreateLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_CreateLog_Call) Return(_a0 int64, _a1 error) *MockStore_CreateLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreateLog_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockStore_CreateLog_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function with given fields: ctx, id
func (_m *MockStore) Log(ctx context.Context, id int64) (domain.Log, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 domain.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Log, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Log); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Log)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockStore_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStore_Expecter) Log(ctx interface{}, id interface{}) *MockStore_Log_Call {
	return &MockStore_Log_Call{Call: _e.mock.On("Log", ctx, id)}
}

func (_c *MockStore_Log_Call) Run(run func(ctx context.Context, id int64)) *MockStore_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStore_Log_Call) Return(_a0 domain.Log, _a1 error) *MockStore_Log_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Log_Call) RunAndReturn(run func(context.Context, int64) (domain.Log, error)) *MockStore_Log_Call {
	_c.Call.Return(run)
	return _c
}

// Node provides a mock function with given fields: ctx, nodeID
func (_m *MockStore) Node(ctx context.Context, nodeID int64) (domain.Node, error) {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for Node")
	}

	var r0 domain.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Node, error)); ok {
		return rf(ctx, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Node); ok {
		r0 = rf(ctx, nodeID)
	} else {
		r0 = ret.Get(0).(domain.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Node_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Node'
type MockStore_Node_Call struct {
	*mock.Call
}

// Node is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID int64
func (_e *MockStore_Expecter) Node(ctx interface{}, nodeID interface{}) *MockStore_Node_Call {
	return &MockStore_Node_Call{Call: _e.mock.On("Node", ctx, nodeID)}
}

func (_c *MockStore_Node_Call) Run(run func(ctx context.Context, nodeID int64)) *MockStore_Node_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStore_Node_Call) Return(_a0 domain.Node, _a1 error) *MockStore_Node_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Node_Call) RunAndReturn(run func(context.Context, int64) (domain.Node, error)) *MockStore_Node_Call {
	_c.Call.Return(run)
	return _c
}

// NodeDetail provides a mock function with given fields: ctx, nodeID
func (_m *MockStore) NodeDetail(ctx context.Context, nodeID int64) (application.NodeDetail, error) {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for NodeDetail")
	}

	var r0 application.NodeDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (application.NodeDetail, error)); ok {
		return rf(ctx, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) application.NodeDetail); ok {
		r0 = rf(ctx, nodeID)
	} else {
		r0 = ret.Get(0).(application.NodeDetail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_NodeDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeDetail'
type MockStore_NodeDetail_Call struct {
	*mock.Call
}

// NodeDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID int64
func (_e *MockStore_Expecter) NodeDetail(ctx interface{}, nodeID interface{}) *MockStore_NodeDetail_Call {
	return &MockStore_NodeDetail_Call{Call: _e.mock.On("NodeDetail", ctx, nodeID)}
}

func (_c *MockStore_NodeDetail_Call) Run(run func(ctx context.Context, nodeID int64)) *MockStore_NodeDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStore_NodeDetail_Call) Return(_a0 application.NodeDetail, _a1 error) *MockStore_NodeDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_NodeDetail_Call) RunAndReturn(run func(context.Context, int64) (application.NodeDetail, error)) *MockStore_NodeDetail_Call {
	_c.Call.Return(run)
	return _c
}

// Nodes provides a mock function with given fields: ctx, logID
func (_m *MockStore) Nodes(ctx context.Context, logID int64) ([]domain.Node, error) {
	ret := _m.Called(ctx, logID)

	if len(ret) == 0 {
		panic("no return value specified for Nodes")
	}

	var r0 []domain.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Node, error)); ok {
		return rf(ctx, logID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Node); ok {
		r0 = rf(ctx, logID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, logID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Nodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nodes'
type MockStore_Nodes_Call struct {
	*mock.Call
}

// Nodes is a helper method to define mock.On call
//   - ctx context.Context
//   - logID int64
func (_e *MockStore_Expecter) Nodes(ctx interface{}, logID interface{}) *MockStore_Nodes_Call {
	return &MockStore_Nodes_Call{Call: _e.mock.On("Nodes", ctx, logID)}
}

func (_c *MockStore_Nodes_Call) Run(run func(ctx context.Context, logID int64)) *MockStore_Nodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStore_Nodes_Call) Return(_a0 []domain.Node, _a1 error) *MockStore_Nodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Nodes_Call) RunAndReturn(run func(context.Context, int64) ([]domain.Node, error)) *MockStore_Nodes_Call {
	_c.Call.Return(run)
	return _c
}

// Ports provides a mock function with given fields: ctx, nodeID
func (_m *MockStore) Ports(ctx context.Context, nodeID int64) ([]domain.Port, error) {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for Ports")
	}

	var r0 []domain.Port
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Port, error)); ok {
		return rf(ctx, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Port); ok {
		r0 = rf(ctx, nodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Port)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Ports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ports'
type MockStore_Ports_Call struct {
	*mock.Call
}

// Ports is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID int64
func (_e *MockStore_Expecter) Ports(ctx interface{}, nodeID interface{}) *MockStore_Ports_Call {
	return &MockStore_Ports_Call{Call: _e.mock.On("Ports", ctx, nodeID)}
}

func (_c *MockStore_Ports_Call) Run(run func(ctx context.Context, nodeID int64)) *MockStore_Ports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStore_Ports_Call) Return(_a0 []domain.Port, _a1 error) *MockStore_Ports_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Ports_Call) RunAndReturn(run func(context.Context, int64) ([]domain.Port, error)) *MockStore_Ports_Call {
	_c.Call.Return(run)
	return _c
}

// SaveResult provides a mock function with given fields: ctx, logID, result
func (_m *MockStore) SaveResult(ctx context.Context, logID int64, result application.ParseResult) error {
	ret := _m.Called(ctx, logID, result)

	if len(ret) == 0 {
		panic("no return value specified for SaveResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, application.ParseResult) error); ok {
		r0 = rf(ctx, logID, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SaveResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveResult'
type MockStore_SaveResult_Call struct {
	*mock.Call
}

// SaveResult is a helper method to define mock.On call
//   - ctx context.Context
//   - logID int64
//   - result application.ParseResult
func (_e *MockStore_Expecter) SaveResult(ctx interface{}, logID interface{}, result interface{}) *MockStore_SaveResult_Call {
	return &MockStore_SaveResult_Call{Call: _e.mock.On("SaveResult", ctx, logID, result)}
}

func (_c *MockStore_SaveResult_Call) Run(run func(ctx context.Context, logID int64, result application.ParseResult)) *MockStore_SaveResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(application.ParseResult))
	})
	return _c
}

func (_c *MockStore_SaveResult_Call) Return(_a0 error) *MockStore_SaveResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SaveResult_Call) RunAndReturn(run func(context.Context, int64, application.ParseResult) error) *MockStore_SaveResult_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function with given fields: ctx, logID, status
func (_m *MockStore) SetStatus(ctx context.Context, logID int64, status domain.LogStatus) error {
	ret := _m.Called(ctx, logID, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.LogStatus) error); ok {
		r0 = rf(ctx, logID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockStore_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - logID int64
//   - status domain.LogStatus
func (_e *MockStore_Expecter) SetStatus(ctx interface{}, logID interface{}, status interface{}) *MockStore_SetStatus_Call {
	return &MockStore_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, logID, status)}
}

func (_c *MockStore_SetStatus_Call) Run(run func(ctx context.Context, logID int64, status domain.LogStatus)) *MockStore_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.LogStatus))
	})
	return _c
}

func (_c *MockStore_SetStatus_Call) Return(_a0 error) *MockStore_SetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SetStatus_Call) RunAndReturn(run func(context.Context, int64, domain.LogStatus) error) *MockStore_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
